I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 536, in script call
    call gameloop
  File "game/script.rpy", line 547, in script call
    call maploop
  File "game/script.rpy", line 648, in script call
    call herbs
  File "game/script.rpy", line 751, in script call
    call maploop
  File "game/script.rpy", line 650, in script call
    call river
  File "game/script.rpy", line 759, in script
    if weatherCold > 2:
  File "game/script.rpy", line 759, in <module>
    if weatherCold > 2:
NameError: name 'weatherCold' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 536, in script call
    call gameloop
  File "game/script.rpy", line 547, in script call
    call maploop
  File "game/script.rpy", line 648, in script call
    call herbs
  File "game/script.rpy", line 751, in script call
    call maploop
  File "game/script.rpy", line 650, in script call
    call river
  File "game/script.rpy", line 759, in script
    if weatherCold > 2:
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 759, in <module>
    if weatherCold > 2:
NameError: name 'weatherCold' is not defined

Darwin-19.5.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
sunsunsun 1.0
Wed Nov  4 20:30:25 2020
