I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 499, in script call
    call gameloop
  File "game/gameloop.rpy", line 5, in script call
    call maploop
  File "game/script.rpy", line 529, in script call
    call woods
  File "game/script.rpy", line 766, in script
    if rollevent == 3: # 1 of the 4 actions
  File "game/script.rpy", line 766, in <module>
    if rollevent == 3: # 1 of the 4 actions
NameError: name 'rollevent' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 499, in script call
    call gameloop
  File "game/gameloop.rpy", line 5, in script call
    call maploop
  File "game/script.rpy", line 529, in script call
    call woods
  File "game/script.rpy", line 766, in script
    if rollevent == 3: # 1 of the 4 actions
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 766, in <module>
    if rollevent == 3: # 1 of the 4 actions
NameError: name 'rollevent' is not defined

Darwin-19.5.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
sunsunsun 1.0
Sun Mar  7 14:05:29 2021
